apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: simple-es
  namespace: simple-observability
spec:
  version: 8.11.1

  podDisruptionBudget:
    spec:
      minAvailable: 1

  nodeSets:
    - name: default
      count: 3

      config:
        node.store.allow_mmap: false
        xpack.ml.enabled: false

      podTemplate:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node-role.kubernetes.io/worker
                        operator: Exists

            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      elasticsearch.k8s.elastic.co/cluster-name: simple-es
                  topologyKey: kubernetes.io/hostname

          containers:
            - name: elasticsearch
              env:
                - name: ES_JAVA_OPTS
                  value: '-Xms768m -Xmx768m'
              resources:
                requests:
                  memory: 1Gi
                  cpu: 500m
                limits:
                  memory: 1500Mi
                  cpu: 1
