apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: simple-kibana
  namespace: simple-observability
spec:
  version: 8.11.1
  count: 1
  elasticsearchRef:
    name: simple-es
  podTemplate:
    spec:
      containers:
        - name: kibana
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
          env:
            - name: NODE_OPTIONS
              value: '--max-old-space-size=512'
